### ISSUE TITLE
Not able to init hangar

### ISSUE THREAD

**Issue by ameen4455** [tensorwerk/hangar-py#142]
`hanger init` threw the error
```
Traceback (most recent call last):
  File "/usr/local/bin/hangar", line 11, in <module>
    load_entry_point('hangar', 'console_scripts', 'hangar')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ameen4455/hangar-py/src/hangar/cli/__init__.py", line 1, in <module>
    from .cli import main
  File "/home/ameen4455/hangar-py/src/hangar/cli/cli.py", line 509, in <module>
    @click.option('--limit', default=30, help='limit the amount of records displayed before truncation')
  File "/usr/lib/python3/dist-packages/click/core.py", line 1163, in decorator
    cmd = command(*args, **kwargs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 89, in _make_command
    callback=f, params=params, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
```

from python terminal
`repo.init('myrepo', user_name='username', user_email='email@.email.com')` threw the error

```
Hangar Repo initialized at: ./.hangar
Traceback (most recent call last):
  File "/home/ameen4455/hangar-py/src/hangar/records/heads.py", line 220, in create_branch
    success = branchtxn.put(branchHeadKey, branchHeadVal, overwrite=False)
lmdb.CorruptedError: mdb_put: MDB_CORRUPTED: Located page was wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ameen4455/hangar-py/src/hangar/repository.py", line 321, in init
    user_name=user_name, user_email=user_email, remove_old=remove_old)
  File "/home/ameen4455/hangar-py/src/hangar/context.py", line 286, in _init_repo
    heads.create_branch(self.branchenv, 'master', '')
  File "/home/ameen4455/hangar-py/src/hangar/records/heads.py", line 226, in create_branch
    TxnRegister().commit_writer_txn(branchenv)
  File "/home/ameen4455/hangar-py/src/hangar/context.py", line 118, in commit_writer_txn
    self.WriterTxn[lmdbenv].commit()
lmdb.BadTxnError: mdb_txn_commit: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid
```

 - OS:
Python:3.6.4
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by rlizzo** [comment]
Hey @ameen4455, sorry to hear you're having issues!

How was this package installed? via `pip` or `conda-forge`?  or via a source build?

Also, if you could run 

```
from hangar import Repository
repo = Repository('./')
repo._ecosystem_details()
```

and report the output it would be helpful!

**Comment by ameen4455** [comment]
Hey! Thanks for the quick reply.
I installed the package using `pip`
Here are the details.
`{'host': [('python', "(3, 6, 8, 'final', 0)"), ('python-bits', '64'), ('OS', 'Linux'), ('OS-release', '4.4.0-17134-Microsoft'), ('machine', 'x86_64'), ('processor', 'x86_64'), ('byteorder', 'little'), ('LC_ALL', 'None'), ('LANG', 'C.UTF-8'), ('LOCALE', "('en_US', 'UTF-8')"), ('cpu-count', '8')], 'packages': [('hangar', '0.3.0'), ('click', '6.7'), ('lmdb', '0.96'), ('h5py', '2.9.0'), ('numpy', '1.17.2'), ('blosc', '1.8.1'), ('tqdm', '4.36.1'), ('wrapt', '1.11.2'), ('grpc', '1.24.1')], 'optional': {'blosc-hdf5-plugin': False, 'pytorch': False, 'tensorflow': False}}`

**Comment by rlizzo** [comment]
No problem! That helps. 

You wouldn't happen to be running this inside the Windows Subsystem for Linux would you?

**Comment by rlizzo** [comment]
Closed due to inactivity.
